version: '3.8'
services:
  frontend:
    image: priyangshuchakraborty/angular-frontend:latest
    ports:
      - "80:80"
  backend:
    image: priyangshuchakraborty/backend-app:latest
    ports:
      - "8080:8080"
